

name: Enforce License Compliance

on:
  pull_request:
    branches: [master]

jobs:
  enforce-license-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}